// <auto-generated />
using Alquiler.BD;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Alquiler.BD.Migrations
{
    [DbContext(typeof(BdContext))]
    [Migration("20221213075132_inicio")]
    partial class inicio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Alquiler.BD.Data.Entidades.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Url = "electrodomestico",
                            nombre = "Electrodomestico"
                        },
                        new
                        {
                            Id = 2,
                            Url = "herramientas",
                            nombre = "Herramientas"
                        },
                        new
                        {
                            Id = 3,
                            Url = "tecnologia",
                            nombre = "Tecnologia"
                        },
                        new
                        {
                            Id = 4,
                            Url = "juguete",
                            nombre = "Juguetes"
                        });
                });

            modelBuilder.Entity("Alquiler.BD.Data.Entidades.Direccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Departamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provincia")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Direcciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Departamento = " Capital ",
                            Localidad = "Cordoba ",
                            Provincia = " Cordoba "
                        },
                        new
                        {
                            Id = 2,
                            Departamento = " Rio Cuarto ",
                            Localidad = " Rio Cuarto",
                            Provincia = " Cordoba "
                        },
                        new
                        {
                            Id = 3,
                            Departamento = " Rio Tercero ",
                            Localidad = "Almafuerte",
                            Provincia = " Cordoba "
                        },
                        new
                        {
                            Id = 4,
                            Departamento = " Rio Tercero ",
                            Localidad = "Oliva",
                            Provincia = " Cordoba "
                        },
                        new
                        {
                            Id = 5,
                            Departamento = " Rio Tercero ",
                            Localidad = "Rio Tercero",
                            Provincia = " Cordoba "
                        },
                        new
                        {
                            Id = 6,
                            Departamento = " Rio Segundo ",
                            Localidad = "Pilar",
                            Provincia = " Cordoba "
                        },
                        new
                        {
                            Id = 7,
                            Departamento = " Rio Segundo ",
                            Localidad = "Oncativo",
                            Provincia = " Cordoba "
                        },
                        new
                        {
                            Id = 8,
                            Departamento = " Rio Segundo ",
                            Localidad = "Rio Segundo",
                            Provincia = " Cordoba "
                        },
                        new
                        {
                            Id = 9,
                            Departamento = " Rio Primero ",
                            Localidad = "La Quinta",
                            Provincia = " Cordoba "
                        },
                        new
                        {
                            Id = 10,
                            Departamento = " Tulumba ",
                            Localidad = "Villa Tulumba",
                            Provincia = " Cordoba "
                        },
                        new
                        {
                            Id = 11,
                            Departamento = " Sobremonte ",
                            Localidad = "San Francisco Del Chañar",
                            Provincia = " Cordoba "
                        },
                        new
                        {
                            Id = 12,
                            Departamento = " Rio Seco ",
                            Localidad = "Cerro Colorado",
                            Provincia = " Cordoba "
                        },
                        new
                        {
                            Id = 13,
                            Departamento = " Cruz del Eje ",
                            Localidad = "San Marcos Sierras",
                            Provincia = " Cordoba "
                        },
                        new
                        {
                            Id = 14,
                            Departamento = " Ischilín ",
                            Localidad = "Parroquia",
                            Provincia = " Cordoba "
                        },
                        new
                        {
                            Id = 15,
                            Departamento = " Totoral ",
                            Localidad = "Las Peñas",
                            Provincia = " Cordoba "
                        },
                        new
                        {
                            Id = 16,
                            Departamento = " San Justo ",
                            Localidad = "Arroyito",
                            Provincia = " Cordoba "
                        },
                        new
                        {
                            Id = 17,
                            Departamento = " Minas ",
                            Localidad = "San Carlos Minas",
                            Provincia = " Cordoba "
                        },
                        new
                        {
                            Id = 18,
                            Departamento = " Punilla ",
                            Localidad = "Villa Carlos Paz",
                            Provincia = " Cordoba "
                        },
                        new
                        {
                            Id = 19,
                            Departamento = " Punilla ",
                            Localidad = "Cosquin",
                            Provincia = " Cordoba "
                        },
                        new
                        {
                            Id = 20,
                            Departamento = " Punilla ",
                            Localidad = "La Falda",
                            Provincia = " Cordoba "
                        },
                        new
                        {
                            Id = 21,
                            Departamento = " Punilla ",
                            Localidad = "Bialet Massé",
                            Provincia = " Cordoba "
                        },
                        new
                        {
                            Id = 22,
                            Departamento = " Punilla ",
                            Localidad = "Huerta Grande",
                            Provincia = " Cordoba "
                        },
                        new
                        {
                            Id = 23,
                            Departamento = " Colon ",
                            Localidad = "Jesus Maria",
                            Provincia = " Cordoba "
                        },
                        new
                        {
                            Id = 24,
                            Departamento = " Colon ",
                            Localidad = "La Calera",
                            Provincia = " Cordoba "
                        },
                        new
                        {
                            Id = 25,
                            Departamento = " Colon ",
                            Localidad = "Unquillo",
                            Provincia = " Cordoba "
                        },
                        new
                        {
                            Id = 26,
                            Departamento = " Pocho ",
                            Localidad = "Salsacate",
                            Provincia = " Cordoba "
                        },
                        new
                        {
                            Id = 27,
                            Departamento = " San Alberto ",
                            Localidad = "Mina Clavero",
                            Provincia = " Cordoba "
                        },
                        new
                        {
                            Id = 28,
                            Departamento = " San Alberto ",
                            Localidad = " Villa Cura Brochero",
                            Provincia = " Cordoba "
                        },
                        new
                        {
                            Id = 29,
                            Departamento = " San Alberto ",
                            Localidad = "San Vicente",
                            Provincia = " Cordoba "
                        },
                        new
                        {
                            Id = 30,
                            Departamento = " Santa Maria ",
                            Localidad = "Alta Gracia",
                            Provincia = " Cordoba "
                        },
                        new
                        {
                            Id = 31,
                            Departamento = " Santa Maria ",
                            Localidad = "Anisacate",
                            Provincia = " Cordoba "
                        },
                        new
                        {
                            Id = 32,
                            Departamento = " Santa Maria ",
                            Localidad = "Las Quintas",
                            Provincia = " Cordoba "
                        },
                        new
                        {
                            Id = 33,
                            Departamento = " San Javier ",
                            Localidad = "Villa Dolores",
                            Provincia = " Cordoba "
                        },
                        new
                        {
                            Id = 34,
                            Departamento = " San Javier ",
                            Localidad = "Villa De Las Rosas",
                            Provincia = " Cordoba "
                        },
                        new
                        {
                            Id = 35,
                            Departamento = " San Javier ",
                            Localidad = "La Paz",
                            Provincia = " Cordoba "
                        },
                        new
                        {
                            Id = 36,
                            Departamento = " Calamuchita ",
                            Localidad = "Santa Rosa De Calamuchita",
                            Provincia = " Cordoba "
                        },
                        new
                        {
                            Id = 37,
                            Departamento = " Calamuchita ",
                            Localidad = "Embalse",
                            Provincia = " Cordoba "
                        },
                        new
                        {
                            Id = 38,
                            Departamento = " Calamuchita ",
                            Localidad = "Villa General Belgrano",
                            Provincia = " Cordoba "
                        },
                        new
                        {
                            Id = 39,
                            Departamento = " San Martin ",
                            Localidad = "Villa Maria",
                            Provincia = " Cordoba "
                        },
                        new
                        {
                            Id = 40,
                            Departamento = " Marcos Juarez ",
                            Localidad = "Arias",
                            Provincia = " Cordoba "
                        },
                        new
                        {
                            Id = 41,
                            Departamento = " Marcos Juarez ",
                            Localidad = " Marcos Juarez",
                            Provincia = " Cordoba "
                        },
                        new
                        {
                            Id = 42,
                            Departamento = " Juarez Celman ",
                            Localidad = "La Carlota",
                            Provincia = " Cordoba "
                        },
                        new
                        {
                            Id = 43,
                            Departamento = " Juarez Celman ",
                            Localidad = "General Cabrera",
                            Provincia = " Cordoba "
                        },
                        new
                        {
                            Id = 44,
                            Departamento = " Roque Saenz Peña ",
                            Localidad = "Laboulaye",
                            Provincia = " Cordoba "
                        },
                        new
                        {
                            Id = 45,
                            Departamento = " Roque Saenz Peña ",
                            Localidad = "General Levalle",
                            Provincia = " Cordoba "
                        },
                        new
                        {
                            Id = 46,
                            Departamento = " Roque Saenz Peña ",
                            Localidad = "Serrano",
                            Provincia = " Cordoba "
                        },
                        new
                        {
                            Id = 47,
                            Departamento = " Roque Saenz Peña ",
                            Localidad = "Rosales",
                            Provincia = " Cordoba "
                        },
                        new
                        {
                            Id = 48,
                            Departamento = " General Roca ",
                            Localidad = "Villa Valeria",
                            Provincia = " Cordoba "
                        });
                });

            modelBuilder.Entity("Alquiler.BD.Data.Entidades.Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Estados")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Estados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estados = "En envio"
                        },
                        new
                        {
                            Id = 2,
                            Estados = "En preparacion"
                        },
                        new
                        {
                            Id = 3,
                            Estados = "En local"
                        },
                        new
                        {
                            Id = 4,
                            Estados = "Entregado"
                        });
                });

            modelBuilder.Entity("Alquiler.BD.Data.Entidades.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("CalleAltura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("DireccionId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("TipoDocumentoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DireccionId");

                    b.HasIndex("TipoDocumentoId");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("Alquiler.BD.Data.Entidades.ProductoPublicado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Alquilado")
                        .HasColumnType("bit");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("DetallesProducto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrecioProducto")
                        .HasColumnType("int");

                    b.Property<string>("foto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("EstadoId");

                    b.ToTable("ProductosPublicados");
                });

            modelBuilder.Entity("Alquiler.BD.Data.Entidades.TipoDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("NombreTipoDocumento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TipoDocumentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NombreTipoDocumento = "DNU"
                        },
                        new
                        {
                            Id = 2,
                            NombreTipoDocumento = "PASAPORTE NACIONAL"
                        },
                        new
                        {
                            Id = 3,
                            NombreTipoDocumento = "DNI"
                        },
                        new
                        {
                            Id = 4,
                            NombreTipoDocumento = "TARJETA DE RESIDENCIA"
                        },
                        new
                        {
                            Id = 5,
                            NombreTipoDocumento = "PASAPORTE EXTRANJERO"
                        });
                });

            modelBuilder.Entity("Alquiler.BD.Data.Entidades.Persona", b =>
                {
                    b.HasOne("Alquiler.BD.Data.Entidades.Direccion", "Direccion")
                        .WithMany("Personas")
                        .HasForeignKey("DireccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alquiler.BD.Data.Entidades.TipoDocumento", "TipoDocumento")
                        .WithMany("Personas")
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Direccion");

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("Alquiler.BD.Data.Entidades.ProductoPublicado", b =>
                {
                    b.HasOne("Alquiler.BD.Data.Entidades.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alquiler.BD.Data.Entidades.Estado", "Estado")
                        .WithMany("Productos")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("Alquiler.BD.Data.Entidades.Direccion", b =>
                {
                    b.Navigation("Personas");
                });

            modelBuilder.Entity("Alquiler.BD.Data.Entidades.Estado", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Alquiler.BD.Data.Entidades.TipoDocumento", b =>
                {
                    b.Navigation("Personas");
                });
#pragma warning restore 612, 618
        }
    }
}
